- name: test1
  hosts: '{{ the_hosts }}'
  vars_files:
  - "/home/navid/PycharmProjects/has/template_items_test.yml"
  become: true
  remote_user: root
  gather_facts: yes
  tasks:
  - name: executing shell command
    shell: "{{ item }}"
    with_items: "{{ commands }}"
